### ISSUE TITLE
Waht is "xf_proj" for?

### ISSUE THREAD

**Issue by JeremyCJM** [mingyuan-zhang/MotionDiffuse#10]
Hi Mingyuan,

I am wondering what is "xf_proj" for in [https://github.com/mingyuan-zhang/MotionDiffuse/blob/main/text2motion/models/transformer.py#L394](url).

Why do you select the word with the maximum embedding value?

Thanks,
Jeremy

**Comment by mingyuan-zhang** [comment]
Hi, `xf_proj` is an overall semantic feature to represent the given language description. I think it's a common choice in NLP and Motion Generation that use the last token to represent the overall characteristics. This is also used in [GLIDE](https://github.com/openai/glide-text2im/blob/69b530740eb6cef69442d6180579ef5ba9ef063e/glide_text2im/text2im_model.py#L106), a typical text-to-image generative model.
