### ISSUE TITLE
About training time and hardware

### ISSUE THREAD

**Issue by xiaoyang-RL9** [mingyuan-zhang/MotionDiffuse#11]
Brilliant work as is shown in this project! However, I'd be appreciate that if you could show your GPU type and total training time.

**Comment by mingyuan-zhang** [comment]
Hi, officially, we use 8 NVIDIA Tesla V100 SXM2(32 GB) to train our models. As for KIT-ML, the whole training costs 10 hours. HumanML3D requires 2 days for training. We are now trying to decrease the batchsize and retrain the number of iterations. We will update these results then.

**Comment by xiaoyang-RL9** [comment]
Thanks a lot ! It is really amazing!
