### ISSUE TITLE
How to implement SMPL skin model?

### ISSUE THREAD

**Issue by fyyakaxyy** [mingyuan-zhang/MotionDiffuse#27]
Hello

First of all thank you very much for posting this repository.

The result of my reproduction is a skeleton model of the human body, how should the SMPL skin model shown in your project be realized?

Thanks in advance

**Comment by mingyuan-zhang** [comment]
Hi, you may use [mmhuman3d](https://github.com/open-mmlab/mmhuman3d) to convert 3D keypoints sequences to SMPL sequences. Then you can use [SMPL Blender Addon](https://github.com/Meshcapade/SMPL_blender_addon) to generate visualization results.

**Comment by fyyakaxyy** [comment]
Thank you very much for your answer. With your help, my problem has been solved!

**Comment by hbkang-slx** [comment]
> Thank you very much for your answer. With your help, my problem has been solved!

mmhuman3d doesn't provide keypoints conversion between humanml3d keypoints and smpl.
Can you explain how you solved it?

**Comment by hbkang-slx** [comment]
> Hi, you may use [mmhuman3d](https://github.com/open-mmlab/mmhuman3d) to convert 3D keypoints sequences to SMPL sequences. Then you can use [SMPL Blender Addon](https://github.com/Meshcapade/SMPL_blender_addon) to generate visualization results.

What functions do I have to use to generate SMPL pose sequences? MMhuman3d doesn't seem to provide a keypoints to pose conversion function.

**Comment by fyyakaxyy** [comment]
> > Thank you very much for your answer. With your help, my problem has been solved!
> 
> mmhuman3d doesn't provide keypoints conversion between humanml3d keypoints and smpl. Can you explain how you solved it?

joint2smpl and blender

**Comment by hbkang-slx** [comment]
The SMPL-addon doesn't seem to support importing pose files, and the SMPL-X addon keeps returning errors when importing pose.pkl files and animation.npy/npz files.
Is manually coding a solution to import the pose information into Blender required?
